import Image from 'next/image'
import Head from 'next/head'
import { Header } from '@/components/header'
import { SideBar } from '@/components/side_bar'
import { TopCards } from '@/components/top_cards'

import { RecentOrders } from '@/components/recent_orders'
import { BarChart } from '@/components/bar_chart'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='flex'>
      <SideBar />
      <main className="bg-gray-200 min-h-screen w-full h-full">
        <Header />
        <TopCards />
        <div className='p-4 grid md:grid-cols-3 grid-cols-1 gap-4'>
          <BarChart />
          <RecentOrders />
        </div>
      </main>
      </div>
    </>
  )
}
